version: "3"

services:
  redis:
      container_name: redis
      image: redis:latest
      restart: always
      ports:
        - 6379:6379
      labels:
        - "name=redis"
        - "mode=standalone"
      command: redis-server
      volumes:
          - ./redis/data:/data
          - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf